### PR TITLE
Synthetic data added

### PR DESCRIPTION
**Pull request by david-salac**
We want to have a nice table structure and synthetic data on the beginning.

### CODE REVIEW

**Comment by grazulis** [comment]
Code looks fine but the ethnicities are very US focused. Can we update to make sure is UK specific? Don't think this needs re-running through chatGPT, just a find and replace on the current values?

**Comment by david-salac** [comment]
I changed:
1. African American -> Black African
2. Hispanic -> Indian

**Comment by CPC22n** [comment]
Looks very interesting. A few suggestions:

1. The ethnicity variable seems to be unbalanced as well. Maybe just change African American to 'Black' and Caucasian and Hispanic recode to 'White British'. Then there'll be 4 categories (White British, Black, Asian, Unknown/Other).
2. In Appointment Status recode 'scheduled' to 'DNA' (i.e. did not attend).
3. For outcome, I was wondering whether we needed a diagnosis field as well, but it may be fine as is.
4. In outcome, for those with a DNA appointment status, this could be set as an empty cell.
5. It's interesting to note that all of the date fields are just a sequence such that the date in each row is 1 day after the date in the row before.
6. Medication rows which correspond to appointments with a status of 'cancelled' or 'DNA' should have all fields as empty cells.
7. The length of medication prescriptions is usally 7, 14, 28, 56 or 84 days I think. So, maybe these values could be recorded as: 10->7; 90->14; 180->28; 365->56.

**Comment by david-salac** [comment]
@grazulis @CPC22n 
Hi both,
So, GitHub seems to be working fine now. I regenerated those tables (it's rather quick; you can see all used commands in the README). I think it should reflect all required changes. Let me know if any further modifications are needed.

**Pull request merged**
